version: '3.8'

services:
  postgres:
    image: mypostgres:1.0
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: testing
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testing -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 5

  liquibase:
    image: liquibase/liquibase:latest-alpine
    container_name: myliquibase
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./liquibase/changelog:/liquibase/changelog/
    working_dir: /liquibase
    command: liquibase update --changeLogFile=/changelog/changelog.xml --url=jdbc:postgresql://postgres:5432/testing --username=testuser --password=docker
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: mypgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ricardo072@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - mynetwork
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

networks:
  mynetwork:
    name: postgres
    driver: bridge
