version: '3.8'

services:
  postgres:
    build: .
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: testing
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ricardo072@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - mynetwork
    tty: true
    depends_on:
      - postgres

networks:
  mynetwork:
    driver: bridge
